---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./site:/usr/share/nginx/html:ro
    ports:
      - 8089:80